#below is the script to provision a VM on oracle virtual box using local windows .box file
	Vagrant.configure("2") do |config|
	config.vm.box = "Win10_020623"
	config.vm.box_url = "file:///C:/Test/Win10_020623.box"

	config.vm.provider "virtualbox" do |vb|
	vb.name = "testvm"
	vb.gui = false
	vb.memory = "2048" # Adjust the memory size as needed
	vb.cpus = "2" # Adjust the number of CPUs as needed
	config.vm.boot_timeout = 400 # Set the timeout to 5 minutes (300 seconds)

	end
	end

# below command is used to create .box file from VM hosted on oracle virtual box, PQEAUTOPF4 is the vm name hosted on vbox

	vagrant package --base PQEAUTOPF4
