trigger:
- master

pool:
  vmimage: 'ubuntu-22.04'

variables: 
  buildConfiguration: 'Release'

steps:
- script: dotnet test
  displayName: run unit tests

- script: dotnet build --configuration $(buildConfiguraion)
  displayName: build application

- script:  docker build -t my-image:v1.0
  displayName: build image

- script: docker push my-image:v1.0
  displayName: push image

# job 

jobs:
- job: Run on windows
  pool: 
    vmimage: "windows-latest"
  steps:
  - script: dotnet test
    displayName: run unit tests

- job: Run on Linux
  pool:
    vmimage: 'ubuntu-latest'
  steps:
  - script: dotnet tests
    displayName: run unit tests 
  
  

