apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
    labels:
      app: myapplication
      tier: backend
spec:
 replicas: 2
 selector:
   matchlables:
     tier: backend 
   template:
     metadata:
       name: redis
       labels:
         tier: backend
     spec:    
      containers:
       - name: redis
         image: redis

# one more deployment defination file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: mywebsite
    tier: frontend
spec:
  replicas: 4
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
  selector:
    matchLabels:
        app: myapp

# one more deployment definition file

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
spec:
  replicas: 2
  selector:
    matchLabels:
      name: busybox-pod
  template:
    metadata:
      labels:
        name: busybox-pod
    spec:
      containers:
      - name: busybox-container
        image: busybox888
        command:
        - sh
        - "-c"
        - echo Hello Kubernetes! && sleep 3600


  # alpine aplicatin deployment defination file

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    tier: frontend
spec:
  replicas: 3
  selector:
   matchLabels:
     type: mobileapplication
  template:
    metadata:
      name: httpd-frontend
      labels:
        type: mobileapplication
    spec:
      containers:
        -  name: alpineapp
           image: httpd:2.4-alpine      




