apiVersion: v1
kind: Pod
metadata: 
  name: Redisdb
  labels:
    name: Redisdb
    app: demo-votingapplication
spec:
  containers:
   - name: redis
     image: redis
     ports:
      - containerPort: 6379
