apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
  - name: example-container
    image: nginx
    resources: 
      memory: "2048Mi"
      cpu: "4000m"
    limits:
      memory: "4096Mi"
      cpu: "8000m"
    