apiVersion: app/v1
kind: Service
metadata:
  name: resultservice
  labels:
    name: resultservice
    app: demo-votingapplication
spec:
  type: NodePort
  ports:
    port: 80
    targetport: 80
  matchLabels:
    name: result-pod
    