apiVersion: v1
kind: Pod
metadata:
  name: result-pod
  labels: 
    name: result-pod
    tier: frontendapp2
    app: demo-votingapplication
spec:
  containers:
   - name: resultpod
     image: kodekloud/examplevotingapp_vote:v1
     ports: 
      - containerPort: 80