color = input("enter any colour: ")
noun = input("enter any person name: ")
pluralnoun = input("enter any plural noun for transportation: ")
weapon = input("enter any weapon name: ")
city1 = input("enter first city name: ")
city2 = input("enter second city name: ")
num = input("enter any whole number: ")
god = input("enter any god name: ")

print("once opon time there were one weapon smugller in " + city1)
print("his name is " + noun)
print("and he always wear " + color + " colour blazer")
print("and he likes to travel in " + pluralnoun)
print("after period of time he caught to Police")
print("and got imprisonment for " + num + " years")
print("after getting released from prison he realised and settled in " + city2)
print("and beccame devote of lord " + god )
print(noun + " left all his deomons")
print ("************THE END*************")